version: '3.4'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - appointmentmgm-sqldata:/var/opt/mssql

  nosqldata:
     ports:
       - "27017:27017"
     volumes:
       - appointmentmgm-nosqldata:/data/db

  cachedata:
     ports:
       - "6379:6379"
     volumes:
       - appointmentmgm-cachedata:/data

  rabbitmq:
     ports:
       - "15672:15672"
       - "5672:5672"

volumes:
  appointmentmgm-sqldata:
    external: false
  appointmentmgm-nosqldata:
    external: false
  appointmentmgm-cachedata:
    external: false