version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosqldata:
    image: mongo

  cachedata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  appointmentschedulegw:
    image: envoyproxy/envoy:v1.11.1